### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by RenaKunisaki** [HarbourMasters64/retro#43]
No idea how the heck to use this but.

```
rena@greymon:…/Retro/retro-0.0.4/linux> cmake .
-- The CXX compiler identification is GNU 12.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.37
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.76.1
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.76.1
-- The C compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at _deps/stormlib-src/CMakeLists.txt:11 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at _deps/stormlib-src/CMakeLists.txt:12 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'STORM_SKIP_INSTALL'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: /usr/lib/libz.so (found version "1.2.13")  
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Linking against dependent libraries statically
-- Configuring done (2.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/rena/games/Shipwright/Retro/retro-0.0.4/linux

rena@greymon:…/Retro/retro-0.0.4/linux> make
[  0%] Generating ephemeral/libflutter_linux_gtk.so, ephemeral/flutter_linux/fl_basic_message_channel.h, ephemeral/flutter_linux/fl_binary_codec.h, ephemeral/flutter_linux/fl_binary_messenger.h, ephemeral/flutter_linux/fl_dart_project.h, ephemeral/flutter_linux/fl_engine.h, ephemeral/flutter_linux/fl_json_message_codec.h, ephemeral/flutter_linux/fl_json_method_codec.h, ephemeral/flutter_linux/fl_message_codec.h, ephemeral/flutter_linux/fl_method_call.h, ephemeral/flutter_linux/fl_method_channel.h, ephemeral/flutter_linux/fl_method_codec.h, ephemeral/flutter_linux/fl_method_response.h, ephemeral/flutter_linux/fl_plugin_registrar.h, ephemeral/flutter_linux/fl_plugin_registry.h, ephemeral/flutter_linux/fl_standard_message_codec.h, ephemeral/flutter_linux/fl_standard_method_codec.h, ephemeral/flutter_linux/fl_string_codec.h, ephemeral/flutter_linux/fl_value.h, ephemeral/flutter_linux/fl_view.h, ephemeral/flutter_linux/flutter_linux.h, _phony_
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      main (file:///opt/flutter/packages/flutter_tools/bin/tool_backend.dart:12:37)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
make[2]: *** [flutter/CMakeFiles/flutter_assemble.dir/build.make:93: flutter/ephemeral/libflutter_linux_gtk.so] Error 255
make[1]: *** [CMakeFiles/Makefile2:200: flutter/CMakeFiles/flutter_assemble.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by sitton76** [comment]
I was able to build the linux version by following the build steps from the flutter docs.

https://docs.flutter.dev/platform-integration/linux/building

You will need to install flutter to build retro however.

**Comment by RenaKunisaki** [comment]
Alright, and to save everyone else who had to Google how the heck to use this thing:

```
$ flutter build linux --release
$ ./build/linux/x64/release/bundle/retro
```
